// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFWNJ2vVLNFx1aI0Zh--lUsys9ND4ePcw',
    appId: '1:683664887510:web:90e14c9f2a6d3929bf4377',
    messagingSenderId: '683664887510',
    projectId: 'dwaya-v2',
    authDomain: 'dwaya-v2.firebaseapp.com',
    storageBucket: 'dwaya-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIXGYsuWayHezhC5Yiccz_qKWVLqbUi5o',
    appId: '1:683664887510:android:c39eb14c7492cb04bf4377',
    messagingSenderId: '683664887510',
    projectId: 'dwaya-v2',
    storageBucket: 'dwaya-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxqceuAIBsrymPxBvLWWqcYea1LHlUkk',
    appId: '1:683664887510:ios:8b99a8c750da6a8fbf4377',
    messagingSenderId: '683664887510',
    projectId: 'dwaya-v2',
    storageBucket: 'dwaya-v2.firebasestorage.app',
    iosBundleId: 'com.example.adminPortal',
  );
}
